name: Continuous Integration in a box
on: [push, pull_request]

jobs:
  Containerized-CI:
    runs-on: ubuntu-18.04
    container: nvcr.io/nvidia/nvhpc:21.2-devel-cuda_multi-ubuntu20.04
    env:
      FC: nvfortran
      CC: nvc
      FCFLAGS: "-Mallocatable=03 -Mstandard -Mbounds -Mchkptr -Kieee -Mchkstk"
      NCHOME: /home/runner/netcdf-c
      NFHOME: /home/runner/netcdf-fortran
      RFMIP_DIR: /home/runner/rfmip-files
    steps:
    - name: Update system packages
      run: apt-get update
    ############################################################################
    #
    # Netcdf C and Fortran
    #
    - name: Install HDF5 library
      run: |
        apt-get install libhdf5-dev libcurl4-gnutls-dev hdf5-helpers
        dpkg -L libhdf5-dev

    - name: Install netcdf C library from source
      if: steps.cache-netcdf-c.outputs.cache-hit != 'true'
      env:
        CPPFLAGS: -I/usr/include/hdf5/serial
        LDFLAGS: -L/usr/lib/x86_64-linux-gnu/hdf5/serial/
      run: |
        source /opt/intel/oneapi/setvars.sh || true
        ${CC} --version
        git clone https://github.com/Unidata/netcdf-c.git --branch v4.7.4
        cd netcdf-c
        ls /usr/include
        ./configure --prefix=${NCHOME}
        make -j
        make install

    - name: Build NetCDF Fortran library
      # Unset any Fortran flags
      # Here too it would be nice to use the environment to specify netcdf-c location
      env:
        CPPFLAGS: -I/home/runner/netcdf-c/include
        LDFLAGS: -L/home/runner/netcdf-c/lib
        LD_LIBRARY_PATH: /home/runner/netcdf-c/lib
        FCFLAGS: -fPIC
      if: steps.cache-netcdf-fortran.outputs.cache-hit != 'true'
      run: |
        echo ${TEST}
        source /opt/intel/oneapi/setvars.sh || true
        ${FC} --version
        git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.5.3
        cd netcdf-fortran
        echo ${CPPFLAGS}
        ./configure --prefix=${NFHOME}
        make -j
        make install
    ############################################################################
    # Checks out repository under $GITHUB_WORKSPACE
    - name: Check out code
      uses: actions/checkout@v2

    - name: Environmental variables
      run: |
        echo "RRTMGP_ROOT=${GITHUB_WORKSPACE}"        >> $GITHUB_ENV
        echo "RRTMGP_BUILD=${GITHUB_WORKSPACE}/build" >> $GITHUB_ENV

    - name: Make library, examples, tests
      env:
        RTE_KERNELS: ${{ matrix.rte-kernels }}
      run: |
        source /opt/intel/oneapi/setvars.sh || true
        cd ${RRTMGP_ROOT}
        ${FC} --version
        make -C build -j 2
        make -C tests -j 1
        make -C examples/all-sky -j 2
        make -C examples/rfmip-clear-sky -j 2
    ############################################################################
    # Set up Python and packages
    #
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.7
    - name: Install python packages
      run: conda install --yes urllib3 netcdf4 xarray dask scipy matplotlib seaborn colorcet
    ############################################################################
    - name: Cache RFMIP files
      id: cache-rfmip-files
      uses: actions/cache@v2
      with:
        path: /home/runner/rfmip-files # Same as #{RFMIP_DIR}
        key: rfmip-files

    - name: Stage RFMIP files
      if: steps.cache-rfmip-files.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${RFMIP_DIR}
        cd ${RFMIP_DIR}
        python ${RRTMGP_ROOT}/examples/rfmip-clear-sky/stage_files.py
    ############################################################################
    # Would be great to encode version info
    - name: Run examples, tests
      env:
        LD_LIBRARY_PATH: /home/runner/netcdf-c/lib
      run: |
        source /opt/intel/oneapi/setvars.sh || true
        export LD_LIBRARY_PATH=${NFHOME}/lib:${LD_LIBRARY_PATH}
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        cp ${RFMIP_DIR}/* .
        python ./run-rfmip-examples.py --block_size 8
        cd  ${RRTMGP_ROOT}/examples/all-sky
        python ./run-allsky-example.py
        cd  ${RRTMGP_ROOT}/tests
        cp ${RRTMGP_ROOT}/examples/rfmip-clear-sky/multiple_input4MIPs_radiation_RFMIP_UColorado-RFMIP-1-2_none.nc test_atmospheres.nc
        ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc
        ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc
    - name: Comparison
      run: |
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        python ./compare-to-reference.py --fail=7.e-4
        cd ${RRTMGP_ROOT}/examples/all-sky
        python ./compare-to-reference.py
        cd ${RRTMGP_ROOT}/tests
        python verification.py
